Sprint 2/issue 2#register user in database
BrightCoders-Institute/reto-reservacion-de-vuelos-reto-reservacion-de-vuelos-team-2 pull request #14
Opened 2023-07-05 22:56 UTC by Raibrr

# Description

- Sign-in implementation with Google.
- Sign-up implementation with Firebase Auth.
- Save the user's data in Firestore.

## Screenshots
-Return a message if sign in with Google.
![image](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-reto-reservacion-de-vuelos-team-2/assets/68169792/058f2de0-30b9-437f-b576-ffcf2790fe9b)

- Return a message if sign up with Firebase Auth
![image](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-reto-reservacion-de-vuelos-team-2/assets/68169792/3afd7eef-5bce-4e0a-a95c-7ae11ad74413)

2023-07-05 23:05 UTC, montsegv-2 approved these changes

2023-07-05 23:20 UTC, FranciscoSenestrari approved these changes

2023-07-05 23:26 UTC, Lizzflores approved these changes
LGTM:D

2023-07-06 00:16 UTC, YilKanda requested changes

2023-07-06 00:16 UTC, YilKanda commented on FlightReservations/babel.config.js
> +	]
Check the indentation of your file

2023-07-06 00:16 UTC, YilKanda commented on FlightReservations/src/auth/SignInWithGoogle.ts
> +}
Check the indentation of your file

2023-07-06 00:16 UTC, YilKanda commented on FlightReservations/src/auth/SignInWithGoogle.ts
> +			console.log(error);
Don't leave debugging code like console.log() on GitHub.

2023-07-06 00:16 UTC, YilKanda commented on FlightReservations/src/auth/SignUp.ts
> +	}
Check the indentation of your file.

Add a blank line.

2023-07-06 00:16 UTC, YilKanda commented on FlightReservations/src/db/AddUserInfo.ts
> +};
Add a blank line.

2023-07-06 00:16 UTC, YilKanda commented on FlightReservations/src/db/AddUserInfo.ts
> +    .catch(error => console.log(error));
Don't leave debugging code like console.log() on GitHub.

2023-07-06 00:16 UTC, YilKanda commented on FlightReservations/types/env.d.ts
> +}
Add a blank line

2023-07-06 00:16 UTC, YilKanda commented on FlightReservations/tsconfig.json
>  }
Add a blank line

2023-07-06 00:16 UTC, YilKanda commented on FlightReservations/src/auth/SignInWithGoogle.ts
> +      .catch(error => console.log('error de usuario existe', error));
Don't leave debugging code like console.log() on GitHub.

2023-07-06 00:16 UTC, YilKanda commented on FlightReservations/.env.example
> +API_URL=
Add a blank line

2023-07-07 18:10 UTC, YilKanda approved these changes

2023-07-07 19:29 UTC, merged