Sprint 3/issue 12# my flights screen
BrightCoders-Institute/reto-reservacion-de-vuelos-reto-reservacion-de-vuelos-team-2 pull request #15
Opened 2023-07-06 23:37 UTC by madera-design

# Description

What did you implemented/Why did you implemented this:

-Create a screen my flights
- Create component Card
- Create component floating button 

## Screenshots

If applicable, include screenshots of the results or screenshots that help to see changes

![WhatsApp Image 2023-07-03 at 12 17 39 PM](https://github.com/BrightCoders-Institute/reto-reservacion-de-vuelos-reto-reservacion-de-vuelos-team-2/assets/67840242/c914c5af-1355-45a4-be65-60ba16e4e158)

2023-07-06 23:47 UTC, ecruz17 commented on FlightReservations/src/components/Navigation/Navigation.tsx
> +      <Stack.Screen name="Login" component={Login} options={{title: ''}} />
You can add directly here the options={{headerShown: false}} to avoid rewriting it on every screen :)

2023-07-06 23:49 UTC, ecruz17 approved these changes
LQBTQ ?? 🚀🏳‍🌈

2023-07-07 00:15 UTC, Lizzflores approved these changes
LGTM!:)

2023-07-07 02:10 UTC, DerekAyala commented on FlightReservations/src/components/BoxIndicator/BoxIndicatorStyles.tsx
> +    backgroundColor: '#5C6EF8',
You can save your colors on a separate file to just import them.

2023-07-07 02:11 UTC, DerekAyala approved these changes
Nice Job 💯

2023-07-07 18:14 UTC, YilKanda requested changes, later dismissed

2023-07-07 18:14 UTC, YilKanda commented on FlightReservations/src/components/Card/Card.tsx
> +      </View>
Check the indentation of your file

2023-07-07 18:14 UTC, YilKanda commented on FlightReservations/src/components/Card/styleCard.tsx
> +});
Check the indentation of your file.

Add a blank line.

2023-07-07 18:14 UTC, YilKanda commented on FlightReservations/src/components/Navigation/Navigation.tsx
> +        // options={{headerShown: false}}
Don't leave code in comments, if you don't use it, delete it.

2023-07-07 18:14 UTC, YilKanda commented on FlightReservations/src/screens/MyFlight/MyFlight.tsx
> +
Put your constant in an external file.

2023-07-07 18:14 UTC, YilKanda commented on FlightReservations/src/screens/MyFlight/MyFlight.tsx
> +  });
The styles also go in a separate file.

2023-07-10 23:52 UTC, FranciscoSenestrari requested changes

2023-07-10 23:52 UTC, FranciscoSenestrari commented on FlightReservations/src/components/BoxIndicator/BoxIndicator.tsx
delete comments

2023-07-11 23:46 UTC, FranciscoSenestrari approved these changes

2023-07-13 00:09 UTC, merged