Install dependencies redux toolkit
BrightCoders-Institute/reto-reservacion-de-vuelos-reto-reservacion-de-vuelos-team-2 pull request #21
Opened 2023-07-11 00:44 UTC by madera-design

# Description

What did you implement/Why did you implement this:

-Install dependencies redux toolkit
- Create files to store

2023-07-11 23:06 UTC, ShadowEnchanter approved these changes

2023-07-11 23:49 UTC, FranciscoSenestrari requested changes

2023-07-11 23:49 UTC, FranciscoSenestrari commented on FlightReservations/src/store/store.tsx
delete  comments

2023-07-12 00:00 UTC, FranciscoSenestrari approved these changes

2023-07-12 00:37 UTC, ecruz17 approved these changes
Okaaay let's go

2023-07-12 23:16 UTC, merged